shop/cart/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('', views.get_main_page, name="main"),
    path('about-us', views.get_about_us_page, name="about"),

    path('products/', views.get_products_page, name='products'),
    path('products/<slug:slug>/', views.get_specific_product, name='specific_product_url_with_slug'),

    path('categories/', views.get_categories, name='categories'),

    # user
    path('registration/', views.get_registration_page, name='registration'),
    path('login/', views.get_login_page, name='login'),
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('logout/', views.logout_user, name='logout_user'),
    path('user-profile/', views.get_user_profile_page, name='profile')
]

shop/orders/urls.py
from django.conf.urls import url, re_path
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    re_path(r'^order/(?P<order_id>\d+)/$', views.order_specific, name='order_specific'),
    re_path(r'^all-orders/', views.order_all, name='order_all'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    re_path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.exceptions import ValidationError

from django.urls import reverse
from django.utils.text import slugify
from django.contrib import messages
import datetime
from django.utils.translation import ugettext as _
from django.core.validators import RegexValidator

from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
# Create your models here.


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=12, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    email_is_verified = models.BooleanField(default=False)

    def get_full_name(self):
        return str(self.user.first_name) + ' ' + str(self.user.last_name)

    def __str__(self):
        return self.user.username + '_profile'


class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name="title")
    image = models.ImageField(verbose_name="Image", default="default.jpg")
    slug = models.SlugField(default='', editable=False, max_length=50, unique=True)

    @property
    def get_valid_url_for_products(self):
        return reverse('products') + '?category=' + str(self.slug)

    def save(self, *args, **kwargs):
        from django.template import defaultfilters
        from unidecode import unidecode

        value = self.title
        self.slug = defaultfilters.slugify(unidecode(value),)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


def validate_amount_of_product(value):
    max_value = 1000
    if value > max_value:
        raise ValidationError(f'Amount could not be bigger than {max_value}')
    else:
        return value


class ProductReward(models.Model):
    tag = models.CharField(max_length=50)

    def __str__(self):
        return self.tag


class Product(models.Model):
    title = models.CharField('Name', max_length=50)
    description = models.TextField('Description', max_length=255, default="Some description ...")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=99.99)
    amount = models.PositiveIntegerField(default=5, validators=[validate_amount_of_product])
    image = models.ImageField(verbose_name="Image", default="default_img.jpg")
    slug = models.SlugField(default='', editable=False, max_length=50, unique=True)
    rewards = models.ManyToManyField(ProductReward, default='No awards')

    @property
    def get_string_price(self):
        return str(self.price) + '$'

    def get_absolute_url(self):
        return reverse('specific_product_url_with_slug', args=(self.slug,))

    def save(self, *args, **kwargs):
        from django.template import defaultfilters
        from unidecode import unidecode

        self.slug = defaultfilters.slugify(unidecode(self.title),)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

shop/main/forms.py
from django import forms

# imports default user stuff.
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.utils.translation import ugettext as _
from django.contrib import messages

from .models import Profile


class UserForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"), widget=forms.PasswordInput,
                                help_text=_("Reenter your password"))
    email = forms.EmailField(label=_('Email'), widget=forms.EmailInput, required=False, help_text='Required')
    first_name = forms.CharField(max_length=50, required=False)
    last_name = forms.CharField(max_length=50, required=False)

    class Meta:
        model = User
        fields = ["username", "email", 'password1', 'password2', 'first_name', 'last_name']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number', 'address']

shop/main/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from cart.forms import CartAddProductForm
from main.models import Product, Category
from .forms import UserForm, ProfileForm
from .models import Profile
from concurrent.futures import ThreadPoolExecutor
import logging
logger = logging.getLogger(__name__)

# Create your views here.


def get_main_page(request):
    return render(request, "main/main.html", {})


def get_about_us_page(request):
    return render(request, "main/about_us.html", {})


def get_user_profile_page(request):
    user = request.user

    return render(request, 'main/user_profile.html', {"user": user})


def logout_user(request):
    user = request.user

    if user.is_authenticated:
        logout(request)

    return redirect('main')


def get_products_page(request):
    chosen_category = request.GET.get("category", "")

    if (chosen_category != ""):
        products = Product.objects.all().filter(category__slug=chosen_category)
    else:
        products = Product.objects.all()

    return render(request, "main/products.html", {'products': products, 'category':chosen_category})


def get_specific_product(request, slug):
    product = Product.objects.get(slug=slug)
    cart_product_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_product_form}
    return render(request, 'main/product.html', context)


def get_categories(request):
    categories = Category.objects.all()
    return render(request, "main/categories.html", {'categories': categories})


# user stuff
def get_login_page(request):
    if (request.method == 'POST'):
        with ThreadPoolExecutor() as executor:
            username_thread = executor.submit(request.POST.get, 'username')
            password_thread = executor.submit(request.POST.get, 'password')

            username = username_thread.result()
            password = password_thread.result()

        try:
            user = User.objects.get(username=username)
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('categories')
            else:
                messages.info(request, 'Username or password is not correct')
                return render(request, 'main/login.html', {})
        except Exception as e:
            messages.error(request, 'No such user')
            logger.info('Wrong input')
            return redirect('login')
    else:
        return render(request, 'main/login.html', {})


def get_registration_page(request):
    if request.method == "POST":
        with ThreadPoolExecutor() as executor:
            username_thread = executor.submit(UserForm, request.POST)
            password_thread = executor.submit(ProfileForm, request.POST)

            user_form = username_thread.result()
            profile_form = password_thread.result()

        # Проверяем есть ли уже пользователь с таким адресом почты.
        email = request.POST.get('email')
        if User.objects.filter(username=request.POST.get('username')).exists():
            messages.error(request, 'This username already registred on site.')
            return redirect('registration')

        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save()
            profile_test = Profile.objects.get(user=new_user)
            profile_test.phone_number = profile_form.cleaned_data.get('phone_number', '')
            profile_test.address = profile_form.cleaned_data.get('address', '')
            profile_test.save()
            return redirect('login')
        else:
            messages.error(request, 'Your data is incorrect')
            return redirect('registration')

    elif request.method == "GET":
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'main/registration.html', {'form': user_form, 'profile_form': profile_form})

shop/templates/main/about_us.html
{% extends "./../base.html" %}

    {% block pre-content %}
        <div class="text-center">
            <h3 class="mbr-section-subtitle align-center pb-3 mbr-fonts-style display-2">
               &#x1F332 Green store &#x1F332
            </h3>
        </div>
    {% endblock %}

    {% block content %}
        <div class="text-center">
            <h5 class="mbr-text align-center pb-3 mbr-fonts-style display-5">
                <b>OUR MISSION</b><br><br>
            </h5>
            <p style="text-align:left">
                &#9679 The main task of the Green hypermarket chain is to provide Belarusians with the opportunity
                to comfortably buy high-quality goods in modern stores;<br>
                &#9679 Quality control of goods at all stages;<br>
                &#9679 Help customers choose products that promote an active lifestyle and do not negatively affect
                their health.<br><br>
            </p>
            <h5 class="mbr-text align-center pb-3 mbr-fonts-style display-5">
                <b>OUR FEATURES</b><br><br>
            </h5>
            <p style="text-align:left">
                &#9679 Farm products and products with natural composition under its own trademark "Local Known";<br>
                &#9679 A full range of products of our own production in the stores of the chain, including finished
                products and sushi;<br>
                &#9679 Emphasis on "healthy" and quality ingredients;<br>
                &#9679 Products for a healthy diet. For example, bran bread, etc.<br><br>
            </p>
            <h5 class="mbr-text align-center pb-3 mbr-fonts-style display-5">
                <b>GREEN TODAY</b><br><br>
            </h5>
            <p style="text-align:left">
                LLC "GRINroznitsa" - one of the leaders in the retail market of Belarus - on December 1 issued
                tokens on the investment platform of Bank BelVEB FINSTORE.by. This is the first deal in Belarus for the
                issue of tokens for retail chains.<br><br><br><br>
            </p>
            <p style="text-align:right">
            With love, your green store!
            </p>
        </div>
    {% endblock %}

shop/templates/main/categories.html
{% extends "./../base.html" %}
    {% block pre-content %}
        <span class="text-center">
            <h4 class="dealing-with-specificity text-primary">
                Product categories
            </h4>
            <p>
                Click category to search corresponding goods
            </p>
        </span>
    {% endblock %}

    {% block content %}
        <!-- PRODUCT CONTENT -->
        <h4 class="text-center">Categories : </h4>
        <div class="album py-5 text-center">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    <!-- Out all our objects -->
                    {% for el in categories %}
                    <!-- Тут генерирую параметры URL запроса для перехода к нужным товарам -->
                    <a class="btn" href={{ el.get_valid_url_for_products }}>
                        <div class="fade-out-siblings">
                            <div class="col">
                                <div class="card shadow-sm">
                                    <img src={{ el.image.url }} class="img-fluid" style="width: auto; height: 200px;">
                                    <h3>{{el.title}}</h3>
                                </div>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>


    {% endblock %}

shop/templates/main/main.html
{% extends "./../base.html" %}
{% load static %}

    {% block pre-content %}
        <span class="text-center">
            <div class="bd-callout bd-callout-info">
                <h4>
                    &#x1F332 Green store &#x1F332
                </h4>
            </div>
        </span>
    {% endblock %}

    {% block content %}
        <div class="container">
            <div class="row g-3">
                <img
                  src="https://thumbs.dreamstime.com/b/christmas-food-flat-lay-text-welcome-sign-english-walnut-hazelnut-
                  cinnamon-sticks-orange-peel-brown-wooden-background-102712430.jpg"
                  class="w-100 shadow-1-strong rounded mb-4"
                  alt=""
                />
            </div>
        </div>
    {% endblock %}

shop/templates/main/product.html
{% extends "./../base.html" %}

{% block content %}
    <style>
        .product-main-block {
            border-radius: 20px;
            border: 1px solid rgb(153, 153, 153);
            background-color: rgba(255,0,0,0.1);
            min-height: 100px;
            padding-bottom: 20px;
        }
        .product-left-block {
            border-right: 1px solid rgb(133, 133, 133);
            min-height: 300px;
        }
        .product-img-nice {
            border: 1px solid rgb(0, 0, 0);
            width: 250px;
            height: 200px;
        }
        .product-img-nice:hover {
            transition: transform .2s; /* Animation */
            transform: scale(1.2);
        }
        .product-img-out {
            padding-top: 20px;
            padding-left: 25px;
        }
    </style>

    <div class="container" style="padding-bottom: 25%;">
        <div class="main-body">

        <!-- Breadcrumb -->
            <nav aria-label="breadcrumb" class="main-breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'main' %}> Home </a></li>
                    <li class="breadcrumb-item"><a href={% url 'products' %}> Products </a></li>
                    <li class="breadcrumb-item"><a href={{ product.category.get_valid_url_for_products }}>
                        {{ product.category.title }} (Category)</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ product.title }} (Product)</li>
                </ol>
            </nav>
            <!-- /Breadcrumb -->

            <div class="product-main-block">
                <div class="container">
                    <div class="row">
                        <div class="product-left-block">
                            <div class="col-md-4">
                                <div class="product-img-out">
                                    <img src={{ product.image.url }} class="product-img-nice">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <h3>{{ product.title }}</h3>
                            <p>Price : {{ product.get_string_price }}</p>
                            <p>Amount : {{ product.amount }}</p>
                            <p>Description : {{ product.description }}</p>
                            {% if product.rewards.count == 0 %}
                                <p>Awards : There's no any awards </p>
                            {% else %}
                                <p>Awards :
                                {% for reward in product.rewards.all %}
                                    {{reward}}
                                    {% if reward != product.rewards.last %}
                                        ,
                                    {% endif %}
                                {% endfor %}
                                </p>
                            {% endif %}
                            {% if product.amount == 0 %}
                                <p class="p-3 mb-2 bg-danger text-white">
                                    Out of stock!
                                </p>
                            {% else %}
                                <!-- Cart Buy stuff --------------------------------------------->
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ cart_product_form }}
                                    <input type="submit" value="Add to cart">
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/main/registration.html
{% extends "./../base.html" %}

{% block content %}
    <div>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.username.label }} {{ form.username }} <br>
            {{ form.first_name.label }} {{ form.first_name }} <br>
            {{ form.last_name.label }} {{ form.last_name }} <br>
            {{ form.email.label }} {{ form.email }} <br>
            {{ profile_form.phone_number.label }} {{ profile_form.phone_number }} <br>
            {{ profile_form.address.label }} {{ profile_form.address }} <br>
            {{ form.password1.label }} {{ form.password1 }} <br>
            {{ form.password2.label }} {{ form.password2 }} <br>
            <button type="submit">Registrate</button>
        </form>
    </div>
{% endblock %}

shop/templates/main/user_profile.html
{% extends "./../base.html" %}

<style>
    body{
        margin-top:20px;
        color: #1a202c;
        text-align: left;
        background-color: #e2e8f0;    
    }
    .main-body {
        padding: 15px;
    }
    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }
    
    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }
    
    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }
    
    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }
    
    .gutters-sm>.col, .gutters-sm>[class*=col-] {
        padding-right: 8px;
        padding-left: 8px;
    }
    .mb-3, .my-3 {
        margin-bottom: 1rem!important;
    }
    
    .bg-gray-300 {
        background-color: #e2e8f0;
    }
    .h-100 {
        height: 100%!important;
    }
    .shadow-none {
        box-shadow: none!important;
    }
</style>

{% block content %}
<div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'main' %}"> Home </a></li>
              <li class="breadcrumb-item active" aria-current="page"> User Profile </li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->          

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <!-- SET  DEFAULT IMAGE FROM STATIC -->
                    <img src="https://st2.depositphotos.com/2703645/5669/v/600/depositphotos_56695433-stock-
                    illustration-female-avatar.jpg" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ user.username }}</h4>
                        {%if user.profile.address is not None%}
                            <p class="text-muted font-size-sm">{{ user.profile.address }}</p>
                        {% else %}
                            <p class="text-muted font-size-sm"> No information </p>
                        {% endif %}
                      <a href="#"><button class="btn btn-primary">Edit</button></a>
                      <a href="#"><button class="btn btn-outline-primary">Message</button></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <span class="text-secondary">https://website.com</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                    <span class="text-secondary">github</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary">@twitter</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary">@inst</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary">facebook</span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {% if user.profile.get_full_name != ' ' %}
                            {{ user.profile.get_full_name }}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {% if user.email != '' %}
                            {{ user.email }}
                        {% else %}
                            No information
                        {% endif %}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {% if user.profile.phone_number != '' and user.profile.phone_number is not None %}
                            {{ user.profile.phone_number }}
                        {% else %}
                            No information
                        {% endif %}
                    </div>
                  </div>                
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {% if user.profile.address != '' and user.profile.address is not None %}
                            {{ user.profile.address }}
                        {% else %}
                            No information
                        {% endif %}
                    </div>
                  </div>
                </div>
              </div>
              <div class="row gutters-sm">

                <!--Cart section ----------------- -->
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">your</i>
                          Cart:</h6>
                      <hr>
                      <a href="{% url 'cart:cart_detail' %}"><button class="btn btn-outline-primary">Cart</button></a>
                    </div>
                  </div>
                </div>

                <!--Orders section ----------------- -->
                <div class="col-sm-6 mb-3">
                    <div class="card h-100">
                      <div class="card-body">
                          <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">
                              your</i>Orders:</h6>
                          <hr>
                          <a href="{% url 'orders:order_all' %}"><button class="btn btn-outline-primary">
                              Show orders</button></a>
                      </div>
                    </div>
                  </div>

                  <!--Logout section ----------------- -->
                <div class="col-sm-6 mb-3">
                    <a href="{% url 'logout_user' %}"><button class="btn btn-outline-primary">
                              Log out</button></a>
                </div>

              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}