shop/cart/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('', views.get_main_page, name="main"),
    path('about-us', views.get_about_us_page, name="about"),

    path('products/', views.get_products_page, name='products'),
    path('products/<slug:slug>/', views.get_specific_product, name='specific_product_url_with_slug'),

    path('categories/', views.get_categories, name='categories'),

    # user
    path('registration/', views.get_registration_page, name='registration'),
    path('login/', views.get_login_page, name='login'),
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('logout/', views.logout_user, name='logout_user'),
    path('user-profile/', views.get_user_profile_page, name='profile')
]

shop/orders/urls.py
from django.conf.urls import url, re_path
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    re_path(r'^order/(?P<order_id>\d+)/$', views.order_specific, name='order_specific'),
    re_path(r'^all-orders/', views.order_all, name='order_all'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    re_path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/cart/forms.py
from django import forms

'''
Generete amount of products user could choice. [0, 19].
or [0, product.quantity]
'''
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(20)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    # False - добавить кол-во товара к существующему.
    # True  - замеенить существующие значение.
    update_quantity = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    '''
    Вызывается из продукта, откуда и берется product_id.
    '''
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        quantity = cd['quantity']
        if quantity > product.amount:
            quantity = product.amount
        cart.add(product=product, quantity=quantity, update_quantity=cd['update_quantity'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')


def cart_detail(request): 
    cart = Cart(request)

    context = {'cart': cart}

    return render(request, 'cart/cart.html', context)

shop/templates/cart/cart.html
{% extends "./../base.html" %}

{% block header %}
    <p style="text-align: center;">
        Your shopping cart:
    </p>
{% endblock header %}

{% block content %}
    <style>
        .coupon-enter-code {

            right: 15%;
            min-width: 30%;
            border-bottom: solid rgb(149, 160, 255);
            border-width: 5px;
            background-color: rgb(226, 226, 226);
        }
        .continue-shopping {
            text-decoration:underline;
            text-align: center;
            min-width: 20px;
            min-height: 20px;
        }
        .continue-shopping:hover {
            border-width: 235px;
            background-color: burlywood;
            color: white;
        }
    </style>

    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Total</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                        {% with product=item.product %}
                            <tr>
                                <td class="col-sm-8 col-md-6">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="#"> <img class="media-object" src={{ product.image.url }} style="width: 150px; height: 110px;"> </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a href="{% url 'specific_product_url_with_slug' product.slug %}">{{ product.title }}</a></h4>
                                        <h5 class="media-heading"> by <a href="#">(Manufacturer)</a></h5>
                                        <span>Status: </span><span class="text-success"><strong> some status</strong></span>
                                    </div>
                                </div></td>
                                <!-- ТУт ввод и отображение кол-ва -->
                                <td class="col-sm-1 col-md-1" style="text-align: center">
                                    <!--<input type="email" class="form-control" id="exampleInputEmail1" value="3">-->
                                    {{ item.quantity }}
                                </td>
                                <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.price }}</strong></td>
                                <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.total_price }}</strong></td>
                                <td class="col-sm-1 col-md-1">
                                <a href="{% url 'cart:cart_remove' product.id %}" style="color: white;">
                                    <button type="button" class="btn btn-danger">
                                        Remove
                                    </button>
                                </a>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                    <tr>
                        <td> &nbsp; </td>
                        <td> &nbsp; </td>
                        <td> &nbsp; </td>
                        <td><h5>Subtotal</h5></td>
                        <td class="text-right"><h5><strong>{{ cart.get_total_price }}$</strong></h5></td>
                    </tr>
                    <tr>
                        <td> &nbsp; </td>
                        <td> &nbsp; </td>
                        <td> &nbsp; </td>
                        <td><h3>Total:</h3></td>
                        <td class="text-right"><h3><strong>{{ cart.get_total_price|floatformat:"2" }}$
                        </strong></h3></td>
                    </tr>
                    <tr>
                        <td> &nbsp; </td>
                        <td> &nbsp; </td>
                        <td> &nbsp; </td>
                        <td>
                            <div class="continue-shopping">
                                <a href="{% url 'products' %}">
                                    Continue Shopping
                                </a>
                            </div>
                        </td>
                        <td>
                            <a href="{% url 'orders:order_create' %}" class="btn btn-success">
                                Checkout
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}